export const HOME = '/'
export const CAROUSEL = '/carousel'
export const GET_BOUNDING_CLIENT_RECT_LAZYLOAD = '/get-bounding-client-rect-lazyload'
export const INTERSECTION_OBSERVER_LAZYLOAD = '/intersection-observer-lazyload'
export const THROTTLE = '/throttle'